# Generated by Django 3.0.6 on 2020-06-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtb',
            name='ccnumber',
        ),
        migrations.RemoveField(
            model_name='wtb',
            name='userid',
        ),
        migrations.AddField(
            model_name='wtb',
            name='addr',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='wtb',
            name='ccexpr',
            field=models.CharField(default='null', max_length=8),
        ),
        migrations.AddField(
            model_name='wtb',
            name='ccname',
            field=models.CharField(default='null', max_length=26),
        ),
        migrations.AddField(
            model_name='wtb',
            name='ccnum',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='wtb',
            name='ccsecc',
            field=models.CharField(default='null', max_length=4),
        ),
        migrations.AddField(
            model_name='wtb',
            name='city',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='wtb',
            name='email',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='wtb',
            name='fname',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='wtb',
            name='lname',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='wtb',
            name='zcode',
            field=models.CharField(default='null', max_length=60),
        ),
    ]
